export const ADMIN_PROD_REQUEST = 'ADMIN_PROD_REQUEST'
export const ADMIN_PROD_SUCCESS = 'ADMIN_PROD_SUCCESS'
export const ADMIN_PROD_FAIL = ' ADMIN_PROD_FAIL'

export const ADMIN_PROD_DEL_REQUEST = 'ADMIN_PROD_DEL_REQUEST'
export const ADMIN_PROD_DEL_SUCCESS = 'ADMIN_PROD_DEL_SUCCESS'
export const ADMIN_PROD_DEL_FAIL = ' ADMIN_PROD_DEL_FAIL'


export const ADMIN_PROD_UPD_REQUEST = 'ADMIN_PROD_UPD_REQUEST'
export const ADMIN_PROD_UPD_SUCCESS = 'ADMIN_PROD_UPD_SUCCESS'
export const ADMIN_PROD_UPD_FAIL = ' ADMIN_PROD_UPD_FAIL'


export const ADMIN_USER_REQUEST = 'ADMIN_USER_REQUEST'
export const ADMIN_USER_SUCCESS = 'ADMIN_USER_SUCCESS'
export const ADMIN_USER_FAIL = ' ADMIN_USER_FAIL'

export const ADMIN_LOAD_PROD_REQUEST = 'ADMIN_LOAD_PROD_REQUEST'
export const ADMIN_LOAD_PROD_SUCCESS = 'ADMIN_LOAD_PROD_SUCCESS'
export const ADMIN_LOAD_PROD_FAIL = ' ADMIN_LOAD_PROD_FAIL'