export const LOAD_PRO_SUCCESS = 'LOAD_PRO_SUCCESS'
export const LOAD_PRO_REQUEST = 'LOAD_PRO_REQUEST'
export const LOAD_PRO_FAIL = 'LOAD_PRO_FAIL'

export const LOAD_SINGLE_SUCCESS = 'LOAD_SINGLE_SUCCESS'
export const LOAD_SINGLE_REQUEST = 'LOAD_SINGLE_REQUEST'
export const LOAD_SINGLE_FAIL = 'LOAD_SINGLE_FAIL'

export const WRITE_REVIEW_SUCCESS = 'WRITE_REVIEW_SUCCESS'
export const WRITE_REVIEW_REQUEST = 'WRITE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const WRITE_REVIEW_FAIL = 'WRITE_REVIEW_FAIL'
